In [3]:
import numpy as np

listo = [1,2,3]
arr = np.array(listo)

arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,4],[1,5,6]]

np.array(my_mat)

array([[1, 2, 4],
       [1, 5, 6]])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
 np.linspace(0,5,10)




array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
np.random.rand(5)

np.random.rand(2,2)

array([[0.02051577, 0.52214427],
       [0.93336693, 0.92347745]])

In [10]:
np.random.randn(4,4)

array([[ 2.21430586, -1.62354756,  0.18772684, -1.02718161],
       [-0.88042858,  0.30307137,  0.06202599, -2.13315571],
       [-1.60048917,  0.02341195, -0.64886674,  0.57646086],
       [-1.29938217,  1.52885276,  0.52697232, -0.15878557]])

In [11]:
np.random.randint(1,100,100)

array([52, 92, 43, 24, 91, 48, 16, 16, 43,  4, 94, 81, 54, 89, 59,  3, 44,
       89, 52, 25, 97, 36, 79, 46, 95, 98, 11, 25,  7, 60, 77, 84, 72, 25,
       94, 78, 44, 57, 84, 38, 99, 48, 52, 24,  4, 54, 99, 77, 95,  8, 14,
       43, 33, 26, 36, 16, 94, 19,  2, 62, 38, 29, 21, 88,  5, 13,  4, 27,
       40, 92, 65, 53, 41, 35, 91, 45, 93,  6, 60, 52, 99, 61, 33, 74, 22,
       46, 68, 69, 84, 92,  8, 38, 16, 48, 85, 91, 24, 65, 90, 69],
      dtype=int32)

In [12]:
pop = np.arange(50)

popl = pop.reshape(5,10)

int(pop.argmax())

49

In [13]:
popl

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
popl[:3,1]

array([ 1, 11, 21])

In [18]:
arrro = popl > 10

In [23]:
popl[arrro]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [26]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
arr1 = np.arange(0,11)

In [28]:
arr1+ arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr1*arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [36]:
nom = np.arange(10,51)

In [38]:
nom[nom % 2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
np.random.rand

array([-1.48814026])

In [53]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [55]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [56]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [58]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [60]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [61]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
co = 0
for i in mat:
    co+=i


co

array([55, 60, 65, 70, 75])

In [69]:
np.sum(mat)

np.std(mat)

np.float64(7.211102550927978)

In [73]:
np.random.rand(6)

array([0.74024128, 0.86289189, 0.26732639, 0.33114647, 0.72541282,
       0.2964929 ])